### ISSUE TITLE
Add GitLab to home page. 

### ISSUE THREAD

**Issue by emilieschario** [gundamew/hugo-bingo#2]
Some people would rather link to GitLab instead of GitHub, or both! This issue would add a `gitlab.svg` to https://github.com/gundamew/hugo-bingo/tree/master/static/img plus whatever changes would need to be made for it to be picked up by the config file for the home page.

Something like: https://about.gitlab.com/images/new_logo/B.jpg but to match the existing aesthetic.

**Comment by gundamew** [comment]
Done. Please check [v1.3.0](https://github.com/gundamew/hugo-bingo/tree/v1.3.0). 😄

**Comment by emilieschario** [comment]
Thank you!
