### ISSUE TITLE
Theme Demo Broken on the Hugo Themes Showcase

### ISSUE THREAD

**Issue by onedrawingperday** [gundamew/hugo-bingo#3]
Hello @gundamew 

You recent commit https://github.com/gundamew/hugo-bingo/commit/3fb3ab1438887ca01c5fe5fb0e55ee2d1d716dc1#diff-1578c58a761c0846adb0e788c860a12bR12 broke your theme's demo. When the website is deployed there is the following console message:

```
4:18:09 PM:  ==== PROCESSING  hugo-bingo  ======
4:18:09 PM: Building site for theme hugo-bingo using default content to ../themeSite/static/theme/hugo-bingo/
4:18:10 PM: Error: Error building site: failed to render pages: render of "home" failed: "/opt/build/repo/hugo-bingo/layouts/index.html:13:27": execute of template failed: template: index.html:13:27: executing "main" at <partial $path (dict "class" "social-media-icon")>: error calling partial: partial "social-icons/%!s(<nil>).svg" not found
4:18:10 PM: FAILED to create exampleSite for hugo-bingo
```
The `.svg` file that you reference under [line 12](https://github.com/gundamew/hugo-bingo/blame/master/layouts/index.html#L12) `/layouts/index.html does not exist in the theme repo.

Either add the `.svg` file or remove the reference.

Once you do the above feel free to close this issue.

Also note that once gohugoio/hugoThemes#668 is addressed you will need to keep an eye on whether the Bingo theme demo generates on the Hugo website.

We are a very small team and we just cannot keep up opening issues in the various theme repositories. Whenever a theme demo breaks and remains broken for a while, then at some point it will be removed from the list without prior warning.

Thank you.

cc: @digitalcraftsman

**Comment by gundamew** [comment]
Thanks for reporting the issue. I'll fix it ASAP. 🙇
