### ISSUE TITLE
recent posts in the home page are empty

### ISSUE THREAD

**Issue by bnicenboim** [gundamew/hugo-bingo#4]
Hi,
I just created the website using the sample posts, and even though they appear under "\posts" they don't appear at the bottom of the homepage.

**Comment by gundamew** [comment]
Hi, thank you for reporting the issue.

**Short answer**: Try to rename the directory from `posts` to `post`.

**Long answer**: This theme display recent posts with the site variable `mainSections` ([home.html#L22-L29](https://github.com/gundamew/hugo-bingo/blob/master/layouts/home.html#L22-L29)). So you can set the variable in root config file with the name(s) of content type(s) you want to display on the homepage. For example:

```toml
# config.toml
[params]
  mainSections = ["blog"]
```

After the content type "blog" is set to one of the variable values. Put your content files in `blog` directory, like `content/blog/my-post.md`. Now restart the Hugo server and the post(s) should be visible on the homepage now.

Reference:

* [`mainSections`](https://gohugo.io/functions/where/#mainsections)
* [Content types](https://gohugo.io/content-management/types/)
* [Front matter](https://gohugo.io/content-management/front-matter/)

**Comment by bnicenboim** [comment]
thanks! It worked
I don't have much experience with blogdown, and your theme looks minimalistic enough for me :)

**Comment by gundamew** [comment]
I'm glad it helped. Happy blogging! 😃
